
#define RFID_RX_PIN 2
#define RFID_TX_PIN 3
#define TAG_TARGET "OSC-01"

#define SECURITY_TIMEOUT_MS (1UL * 60UL * 1000UL)

#define TASK_SENSOR_PRIORITY (tskIDLE_PRIORITY + 3) // High
#define TASK_LOGIC_PRIORITY (tskIDLE_PRIORITY + 2)  // Middle
#define TASK_ALARM_PRIORITY (tskIDLE_PRIORITY + 1)  // Low
